### ISSUE TITLE
Missing file Los fuereños de José Tomás de Cuéllar | nh0129

### ISSUE THREAD

**Issue by silviaegt** [cligs/conha19#1]
Hi @hennyu !
I am for the first time exploring your awesome corpus, and I found out one file is missing, i.e.  _Los fuereños_ de José Tomás de Cuéllar (with idno nh0129)
Hope this information is useful!

**Comment by hennyu** [comment]
Hi @silviaegt , thank you very much for your interest in the corpus. The file nh0129 is not published here because it is still under ancillary copyright in Germany. The edition that I used to extract the text was quite new. You can find some information on rights issues on the start page of this repository, in the section: "Rights and citation suggestions".
